alertmanager:
  enabled: false
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - alertmanager.rizkidoank.internal

    paths:
    - /

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  adminPassword: prom-operator

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - grafana.rizkidoank.internal
    path: /

prometheus:
  enabled: true
  thanosIngress:
    enabled: enabled
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - thanos-gateway.rizkidoank.internal
    paths:
    - /
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    hosts:
      - prometheus.rizkidoank.internal
    paths:
    - /
