apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-control-plane
spec:
  profile: default
  components:
    ingressGateways:
    - name: istio-infrastructure
      namespace: infrastructure
      enabled: true
      k8s:
        service: LoadBalancer
        loadBalancerIP: 192.168.2.151

