apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-ingress-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/rizkidoank/kubernetes-ops.git
    targetRevision: develop
    path: manifests/ingress
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    validate: true
